In [392]:
import csv
import pandas as pd
import numpy as np
import math 

    # create array
myArray = []

    # create variable for import
data = pd.read_csv("monday.csv")

    # clean data -- good job, this is exactly what jupyter notebooks is for... youll need to do more of this kind of thing... for instances I removed the spaces from the 
    # csv file manually.... cant have spaces in names or will cause errors elsewhere
data.dropna(subset=['ROUTE'], axis = 'rows', how ='all', inplace = True) 
data.fillna(0,inplace = True)
#print(data)

#----- Below are the statistics we will need



#count the number of ALL routes
data['IN'] = data['IN'].astype(float)
numOfRoutes = data['IN'].value_counts()[1]

#count number of LVP and LWP respectively
numOfLVP = int(data['LVP'].sum())
numOfLWP = int(data['LWP'].sum())


#here I just print out the results
names = ['Routes: ', 'LVP: ', 'LWP: ']
#print(names)
values = [str(numOfRoutes), str(numOfLWP),str(numOfLVP)]
#print(values)
nl = '\n'
myNum = len(values)

for i in names:
    n1 = names[0] + f" " + values[0] + f"{nl}"
    n2 = names[1] + f" " + values[1]+ f"{nl}"
    n3 = names[2] + f" " + values[2]+ f"{nl}"
    text = f"Statistics for t2oday:{nl}{nl}"
print(text,n1,n2,n3)




#----below is will just keep some commands i have used don't need it if you are not
#using jyouter maybe

#data.shape
#data.columns
#data.head(25)

ValueError: could not convert string to float: ''

In [402]:
    # create variable for import
data = pd.read_csv("wednesday.csv")

    # clean data -- good job, this is exactly what jupyter notebooks is for... youll need to do more of this kind of thing... for instances I removed the spaces from the 
    # csv file manually.... cant have spaces in names or will cause errors elsewhere
data.dropna(subset=['ROUTE'], axis = 'rows', how ='all', inplace = True) 
data.fillna(0,inplace = True)
print(data)

#----- Below are the statistics we will need



#count the number of ALL routes
data['IN'] = data['IN'].astype(float)
numOfRoutes = data['IN'].value_counts()[1]
print(numOfRoutes)

                     NAME   IN ROUTE LOG IN LOG OUT  TORH  MILEAGE  PARCEL  \
2           ARTUR KOSCIEN  1.0  A175  10:15   17:29  7:14    122.0   223.0
4          BLAZEJ KOSTERA  1.0  A176  10:15   17:56  7:41    139.0   209.0
9          DIMITAR PETKOV  1.0  A179  10:15   18:53  8:38     92.0   210.0
10          DIMITAR VALEV  1.0  A182  10:15   18:37  8:22    106.0   204.0
14        GREGORY STREETE  1.0  A177  10:15   17:24  7:09    104.0   210.0
15        ILIYAN STOYANOV  1.0  A184  10:15   17:36  7:21    162.0   180.0
18   KRZYSZTOF WIECZYNSKI  1.0  A189  10:15   17:10  6:55    155.0   176.0
19       NORBERT LINDMANN  1.0  A192  10:15   17:06  6:51    152.0   137.0
21       PAWEL CHMILEWSKI  1.0  A183  10:15   17:46  7:31    126.0   203.0
23        PHLIP EDMONDSON  1.0  A188  10:15   17:11  6:56    143.0   203.0
24           RYAN CADDICK  1.0  A187  10:15   18:08  7:53    161.0   206.0
25        SIMEON DIMITROV  1.0  A178  10:15   15:30  5:15     87.0   164.0
26           STOYAN TENEV  1.0  A193  10:15   18:47  8:32    288.0    78.0
27         SZYMON KAPINOS  1.0  A185  10:15   17:02  6:47    143.0   195.0
28        VESELIN VASILEV  0.0   MFN  13:30   16:21  2:51    102.0    37.0
29  WIKTOR ALEKSANDROWICZ  1.0  A186  10:15   18:56  8:41    170.0   167.0
30    WOJCIECH WISNIEWSKI  1.0  A190  10:15   18:46  8:31    163.0   209.0
31          ZHELYO ZHELEV  1.0  A180  10:15   17:36  7:21     90.0   196.0

    LWP  LVP  CRT   RL     SUP  FUEL  SUPPORT  VANS
2   0.0  1.0  0.0  0.0  18.00   0.0      0.0    0.0
4   0.0  1.0  0.0  0.0  18.00   0.0      0.0    0.0
9   0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
10  0.0  1.0  0.0  0.0  18.00   0.0      0.0    0.0
14  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
15  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
18  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
19  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
21  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
23  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
24  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
25  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
26  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
27  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
28  0.0  0.0  0.0  0.0  80.00   0.0      0.0    0.0
29  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
30  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
31  0.0  0.0  0.0  0.0  18.00   0.0      0.0    0.0
17

In [306]:
names = ['Routes: ', 'LVP: ', 'LWP: ']
#print(names)
values = [str(numOfRoutes), str(numOfLWP),str(numOfLVP)]
#print(values)
nl = '\n'
myNum = len(values)

for i in names:
    n1 = names[0] + f" " + values[0] + f"{nl}"
    n2 = names[1] + f" " + values[1]+ f"{nl}"
    n3 = names[2] + f" " + values[2]+ f"{nl}"
    text = f"Statistics for today:{nl}{nl}"
print(text,n1,n2,n3)

Statistics for today:

 Routes:  16
 LVP:  0
 LWP:  2

In [347]:
data['IN'] = data['IN'].astype(float)
numOfRoutes = data['IN'].value_counts()[1]
print(numOfRoutes)
data.head(26)
data['IN'].count()

19

19

In [243]:
myNum = len(values)
print(myNum)

3

In [324]:
#count number of LVP and LWP respectively
numOfLVP = int(data['LVP'].sum())
numOfLWP = int(data['LWP'].sum())

In [325]:
print(numOfLVP)

3

In [343]:
data.head(22)

,NAME,IN,ROUTE,LOG IN,LOG OUT,TORH,MILEAGE,PARCEL,LWP,LVP,CRT,RL,SUP,FUEL,SUPPORT,VANS
2,ARTUR KOSCIEN,1.0,A181,10:25,19:06,8:41,91.0,235.0,0.0,1.0,0.0,0.0,18.00,0.0,0.0,0.0
4,BLAZEJ KOSTERA,1.0,A189,10:25,17:57,7:32,122.0,209.0,0.0,1.0,0.0,0.0,18.00,0.0,0.0,0.0
8,DANIEL PETROV,1.0,A185,10:25,18:07,7:42,107.0,200.0,0.0,1.0,0.0,0.0,18.00,0.0,0.0,0.0
9,DIMITAR PETKOV,1.0,A190,10:25,18:10,7:45,118.0,203.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
10,DIMITAR VALEV,1.0,A188,10:25,18:53,8:28,130.0,237.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
11,DYLAN PAUL ROBERTS,1.0,A182,10:25,16:22,5:57,78.0,97.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
12,EDWARD LOCK,1.0,A183,10:25,16:46,6:21,80.0,173.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
13,GALIN PETKOV\n,1.0,A179,10:25,18:38,8:13,91.0,175.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
15,ILIYAN STOYANOV,1.0,A194,10:25,16:51,6:26,135.0,205.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
17,JAROSLAW ADAMIEC,1.0,A179,10:25,17:51,7:26,99.0,177.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
19,NORBERT LINDMANN,1.0,A196,10:25,17:03,6:38,157.0,187.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
20,PAVLIN TODOROV,1.0,A186,10:25,17:35,7:10,116.0,172.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
21,PAWEL CHMILEWSKI,1.0,A195,10:25,18:13,7:48,177.0,167.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
23,PHLIP EDMONDSON,1.0,A197,10:25,17:53,7:28,150.0,215.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
24,RYAN CADDICK,1.0,A191,10:25,18:06,7:41,151.0,215.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
26,STOYAN TENEV,1.0,A187,10:25,19:22,8:57,124.0,229.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
28,VESELIN VASILEV,1.0,A178,10:25,19:32,9:07,145.0,186.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
29,WIKTOR ALEKSANDROWICZ,1.0,A192,10:25,20:03,9:38,151.0,204.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0
30,WOJCIECH WISNIEWSKI,1.0,A193,10:25,18:50,8:25,152.0,184.0,0.0,0.0,0.0,0.0,18.00,0.0,0.0,0.0

In [377]:
data.head(25)

,NAME,IN,ROUTE,LOG_IN,LOG_OUT,TORH,MILEAGE,PARCEL,LWP,LVP,...,SUP,FUEL,SUPPORT,VANS,FDDS,PHR,CALL,POD,CONS,DAILY DPMO
CARLOS LOPEZ,1.0,A155,10:15,18:52,8:37,125.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DIMITAR PETKOV,1.0,A159,10:15,18:04,7:49,101.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DIMITAR VALEV,1.0,A156,10:15,18:54,8:39,124.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DYLAN PAUL ROBERTS,1.0,A169,10:15,18:33,8:18,150.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ILIYAN STOYANOV,1.0,A167,10:15,16:28,6:13,148.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
JAN WADOWSKI,0.0,A153,10:15,16:22,6:07,60.0,0.0,0.0,0.0,0.0,...,0.0,60.90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
KRZYSZTOF WIECZYNSKI,1.0,A168,10:15,16:23,6:08,150.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NORBERT LINDMANN,1.0,A153,10:15,14:49,4:34,59.0,0.0,0.0,0.0,0.0,...,0.0,60.90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PAVLIN TODOROV,1.0,A157,10:15,16:28,6:13,122.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PAWEL PLONKA,1.0,A161,10:15,15:30,5:15,79.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RYAN CADDICK,1.0,A154,10:15,16:51,6:36,130.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SIMEON DIMITROV,1.0,A166,10:15,16:46,6:31,133.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
STOYAN TENEV,1.0,A162,10:15,18:10,7:55,90.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
VESELIN VASILEV,1.0,A165,10:15,16:46,6:31,103.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
WIKTOR ALEKSANDROWICZ,1.0,A158,10:15,17:13,6:58,133.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZHELYO ZHELEV,1.0,A163,10:15,17:53,7:38,83.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SABRI SABRIEV,1.0,A160,10:15,15:10,4:55,78.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NINA PAVLOVA,1.0,A164,10:15,13:55,3:40,80.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0